//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnosticos()
        {
            this.Historias = new HashSet<Historias>();
        }
    
        public int IdDiagnostico { get; set; }
        public string DniPaciente { get; set; }
        public int Esquizoide { get; set; }
        public int Evitativo { get; set; }
        public int Depresivo { get; set; }
        public int Dependiente { get; set; }
        public int Histriónico { get; set; }
        public int Narcisista { get; set; }
        public int Antisocial { get; set; }
        public int AgresivoSádico { get; set; }
        public int Compulsivo { get; set; }
        public int Negativista { get; set; }
        public int Autodestructiva { get; set; }
        public int Esquizotípica { get; set; }
        public int Límite { get; set; }
        public int Paranoide { get; set; }
        public int Ansiedad { get; set; }
        public int Somatoformo { get; set; }
        public int Bipolar { get; set; }
        public int Distímico { get; set; }
        public int DependenciaAlcohol { get; set; }
        public int DependenciaSustancias { get; set; }
        public int EstrésPostraumático { get; set; }
        public int DesordenPensamiento { get; set; }
        public int DepresiónMayor { get; set; }
        public int DesordenDelusional { get; set; }
        public int Sinceridad { get; set; }
        public int DeseabilidadSocial { get; set; }
        public int Devaluación { get; set; }
        public int Validez { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFinal { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historias> Historias { get; set; }
    }
}
