//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historias
    {
        public int IdHistoria { get; set; }
        public string Codigo { get; set; }
        public int CodigoDiagnostico { get; set; }
        public string DniPsicologo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public string Tratamiento { get; set; }
        public string Observacion { get; set; }
    
        public virtual Diagnosticos Diagnosticos { get; set; }
        public virtual Psicologos Psicologos { get; set; }
    }
}
